### ISSUE TITLE
Empty lprqueuename causes Test to fail

### ISSUE THREAD

**Issue by derek-robinson** [limiteddenial/PrintManagementDsc#25]
https://github.com/limiteddenial/PrintManagementDsc/blob/9697a4de0952ff11f14444e5b30186b6ba3910d3/DSCClassResources/Printer/Printer.psm1#L603-L607

An empty LprQueueName isn't a null variable, but an empty string. This is causing the Test to come back as a failure. I was able to correct this internally by changing the default value to an empty string, but didn't know if this would break other use cases
```powershell
    [DscProperty()]
    [System.String]
    $lprQueueName = ''
```

```powershell
PS C:\> $p.LprQueueName -eq ''
True
PS C:\> $p.LprQueueName -eq $null
False
```

**Comment by limiteddenial** [comment]
I will have to look to see if this would break any of the use cases. I am working on fixing the tests to verify it. I don't think this would break anything.

**Comment by e-St** [comment]
Hello, just wanted to add, that I have the same issue. derek's fix worked for me. Since I only use TCPIP printers, the fix should not adversely affect my systems.
It would still be good if this would be fixed in the standard version.
Thank you!

**Comment by limiteddenial** [comment]
I'll get this added to the standard version asap
